2023-06-21 04:09:54,520 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-06-21 04:10:06,069 django.request WARNING  Not Found: /
2023-06-21 04:10:07,103 django.request WARNING  Not Found: /
2023-06-21 04:27:33,050 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-06-21 04:27:35,520 django.request WARNING  Not Found: /
2023-06-21 04:27:40,389 django.request WARNING  Not Found: /admin/
2023-06-21 04:31:29,862 django.utils.autoreload INFO     /Users/ehernandep/Documents/nubi/nubi_backend/apps/rating/models.py changed, reloading.
2023-06-21 04:31:30,359 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-06-21 04:46:52,657 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-06-21 04:46:54,369 django.request ERROR    Internal Server Error: /api/v1/auth/users
Traceback (most recent call last):
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via POST, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining POST data. Change your form to point to localhost:8000/api/v1/auth/users/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-06-21 04:47:03,957 django.request WARNING  Bad Request: /api/v1/auth/users/
2023-06-21 04:47:15,002 django.request WARNING  Bad Request: /api/v1/auth/users/
2023-06-21 04:49:51,064 django.request WARNING  Unauthorized: /api/v1/auth/jwt/create/
2023-06-21 04:50:02,157 django.request WARNING  Unauthorized: /api/v1/auth/jwt/create/
2023-06-21 05:02:21,952 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-06-21 05:03:45,499 django.request WARNING  Unauthorized: /api/v1/profile/me/
2023-06-21 05:04:00,613 django.request WARNING  Unauthorized: /api/v1/profile/me/
2023-06-21 05:06:36,663 django.request WARNING  Method Not Allowed: /api/v1/profile/me/
2023-06-21 05:06:45,402 django.request WARNING  Method Not Allowed: /api/v1/profile/me/
2023-06-21 05:07:18,040 django.request WARNING  Not Found: /api/v1/profile/ehernandepp
2023-06-21 05:07:30,810 django.request ERROR    Internal Server Error: /api/v1/profile/update/ehernandepp
Traceback (most recent call last):
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PUT, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PUT data. Change your form to point to localhost:8000/api/v1/profile/update/ehernandepp/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-06-21 05:07:38,564 django.request ERROR    Internal Server Error: /api/v1/profile/update/ehernandepp
Traceback (most recent call last):
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/utils/deprecation.py", line 136, in __call__
    response = self.process_response(request, response)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/middleware/common.py", line 108, in process_response
    return self.response_redirect_class(self.get_full_path_with_slash(request))
                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/middleware/common.py", line 87, in get_full_path_with_slash
    raise RuntimeError(
RuntimeError: You called this URL via PATCH, but the URL doesn't end in a slash and you have APPEND_SLASH set. Django can't redirect to the slash URL while maintaining PATCH data. Change your form to point to localhost:8000/api/v1/profile/update/ehernandepp/ (note the trailing slash), or set APPEND_SLASH=False in your Django settings.
2023-06-21 05:07:48,719 django.request WARNING  Method Not Allowed: /api/v1/profile/update/ehernandepp/
2023-06-21 05:07:54,189 django.request ERROR    Internal Server Error: /api/v1/profile/update/ehernandepp/
Traceback (most recent call last):
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/ehernandep/Documents/nubi/nubi_backend/apps/profiles/views.py", line 70, in patch
    serializer.save()
  File "/Users/ehernandep/Documents/nubi/nubi/lib/python3.11/site-packages/rest_framework/serializers.py", line 184, in save
    assert not self.errors, (
AssertionError: You cannot call `.save()` on a serializer with invalid data.
2023-06-21 05:09:20,918 django.request WARNING  Unauthorized: /api/v1/profile/agents/all/
2023-06-21 05:11:06,693 django.request WARNING  Unauthorized: /api/v1/profile/top-agents/all/
2023-07-11 05:12:24,794 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-11 05:45:04,938 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-11 05:50:39,071 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-11 05:56:53,500 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:15:13,091 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:20:01,595 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:23:23,744 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:24:11,121 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:31:52,540 django.utils.autoreload INFO     /app/backend_nubi/settings/base.py changed, reloading.
2023-07-12 05:31:53,648 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:33:01,654 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:35:42,725 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:38:13,123 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:41:21,120 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:44:41,604 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:46:51,606 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:48:58,166 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:52:58,644 django.utils.autoreload INFO     /app/backend_nubi/settings/development.py changed, reloading.
2023-07-12 05:52:59,599 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-12 05:53:06,510 django.request WARNING  Not Found: /admin
2023-07-12 05:53:06,655 django.request WARNING  Not Found: /favicon.ico
2023-07-12 05:53:20,793 django.request WARNING  Not Found: /
2023-07-12 05:53:30,424 django.request ERROR    Internal Server Error: /supersecret/login/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 441, in login
    return LoginView.as_view(**defaults)(request)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/debug.py", line 92, in sensitive_post_parameters_wrapper
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/views.py", line 90, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/generic/edit.py", line 144, in get
    return self.render_to_response(self.get_context_data())
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/views.py", line 114, in get_context_data
    current_site = get_current_site(self.request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sites/shortcuts.py", line 16, in get_current_site
    return Site.objects.get_current(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sites/models.py", line 59, in get_current
    return self._get_site_by_id(site_id)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sites/models.py", line 30, in _get_site_by_id
    site = self.get(pk=site_id)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_site" does not exist
LINE 1: ..."django_site"."domain", "django_site"."name" FROM "django_si...
                                                             ^

2023-07-12 05:58:22,775 django.request ERROR    Internal Server Error: /supersecret/properties/property/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "properties_property" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "properties_property"
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 123, in __init__
    self.get_results(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 279, in get_results
    result_count = paginator.count
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 557, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 543, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "properties_property" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "properties_property"
                                          ^

2023-07-12 05:58:41,329 django.request ERROR    Internal Server Error: /supersecret/properties/propertyviews/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "properties_propertyviews" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "properties_propertyviews"
                                          ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 688, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 242, in inner
    return view(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 46, in _wrapper
    return bound_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1926, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/options.py", line 836, in get_changelist_instance
    return ChangeList(
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 123, in __init__
    self.get_results(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 279, in get_results
    result_count = paginator.count
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/site-packages/django/core/paginator.py", line 93, in count
    return c()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 608, in count
    return self.query.get_count(using=self.db)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 557, in get_count
    return obj.get_aggregation(using, {"__count": Count("*")})["__count"]
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/query.py", line 543, in get_aggregation
    result = compiler.execute_sql(SINGLE)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "properties_propertyviews" does not exist
LINE 1: SELECT COUNT(*) AS "__count" FROM "properties_propertyviews"
                                          ^

2023-07-13 05:12:05,418 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:12:21,848 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:12:24,504 django.request ERROR    Internal Server Error: /supersecret/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 230, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 266, in inner
    self._setup()
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 53, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

2023-07-13 05:13:01,853 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:14:45,118 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:15:59,849 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:16:03,176 django.request ERROR    Internal Server Error: /supersecret/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 187, in _get_session
    return self._session_cache
AttributeError: 'SessionStore' object has no attribute '_session_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
psycopg2.errors.UndefinedTable: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 261, in wrapper
    return self.admin_view(view, cacheable)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/utils/decorators.py", line 134, in _wrapper_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/views/decorators/cache.py", line 62, in _wrapper_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 230, in inner
    if not self.has_permission(request):
  File "/usr/local/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 203, in has_permission
    return request.user.is_active and request.user.is_staff
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 266, in inner
    self._setup()
  File "/usr/local/lib/python3.8/site-packages/django/utils/functional.py", line 419, in _setup
    self._wrapped = self._setupfunc()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 25, in <lambda>
    request.user = SimpleLazyObject(lambda: get_user(request))
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/middleware.py", line 11, in get_user
    request._cached_user = auth.get_user(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 191, in get_user
    user_id = _get_user_session_key(request)
  File "/usr/local/lib/python3.8/site-packages/django/contrib/auth/__init__.py", line 60, in _get_user_session_key
    return get_user_model()._meta.pk.to_python(request.session[SESSION_KEY])
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 53, in __getitem__
    return self._session[key]
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/base.py", line 192, in _get_session
    self._session_cache = self.load()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 42, in load
    s = self._get_session_from_db()
  File "/usr/local/lib/python3.8/site-packages/django/contrib/sessions/backends/db.py", line 32, in _get_session_from_db
    return self.model.objects.get(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 633, in get
    num = len(clone)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 380, in __len__
    self._fetch_all()
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 1881, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 91, in __iter__
    results = compiler.execute_sql(
  File "/usr/local/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1562, in execute_sql
    cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 102, in execute
    return super().execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 67, in execute
    return self._execute_with_wrappers(
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
  File "/usr/local/lib/python3.8/site-packages/django/db/utils.py", line 91, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/usr/local/lib/python3.8/site-packages/django/db/backends/utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
django.db.utils.ProgrammingError: relation "django_session" does not exist
LINE 1: ...ession_data", "django_session"."expire_date" FROM "django_se...
                                                             ^

2023-07-13 05:19:53,452 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:19:54,201 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:20:04,456 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:20:05,005 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:20:07,155 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:20:07,675 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:20:21,973 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:20:22,516 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:20:29,730 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:20:30,291 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:20:34,457 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:20:35,004 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:26:04,162 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:26:04,944 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:29:17,004 django.utils.autoreload INFO     /app/apps/properties/models.py changed, reloading.
2023-07-13 05:29:17,915 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:29:22,124 django.utils.autoreload INFO     /app/apps/properties/models.py changed, reloading.
2023-07-13 05:29:22,848 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:33:20,889 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:33:21,562 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:33:22,730 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:33:23,247 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:33:25,396 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:33:25,924 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:33:36,150 django.utils.autoreload INFO     /app/apps/properties/apps.py changed, reloading.
2023-07-13 05:33:36,874 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:36:01,903 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:38:06,134 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:45:57,795 django.utils.autoreload INFO     /app/apps/properties/models.py changed, reloading.
2023-07-13 05:45:58,735 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:46:21,266 django.utils.autoreload INFO     /app/apps/properties/models.py changed, reloading.
2023-07-13 05:46:22,124 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:46:23,269 django.utils.autoreload INFO     /app/apps/properties/models.py changed, reloading.
2023-07-13 05:46:23,977 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:46:59,830 django.utils.autoreload INFO     /app/apps/properties/models.py changed, reloading.
2023-07-13 05:47:00,754 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:47:28,419 django.utils.autoreload INFO     /app/apps/properties/models.py changed, reloading.
2023-07-13 05:47:29,220 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:47:30,373 django.utils.autoreload INFO     /app/apps/properties/models.py changed, reloading.
2023-07-13 05:47:31,184 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:48:52,542 django.utils.autoreload INFO     /app/apps/properties/admin.py changed, reloading.
2023-07-13 05:48:53,429 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:48:59,800 django.utils.autoreload INFO     /app/apps/properties/admin.py changed, reloading.
2023-07-13 05:49:00,575 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:49:12,009 django.utils.autoreload INFO     /app/apps/properties/admin.py changed, reloading.
2023-07-13 05:49:12,816 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:49:19,171 django.utils.autoreload INFO     /app/apps/properties/admin.py changed, reloading.
2023-07-13 05:49:19,935 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:50:00,311 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:50:14,929 django.utils.autoreload INFO     Watching for file changes with StatReloader
2023-07-13 05:50:43,678 django.utils.autoreload INFO     Watching for file changes with StatReloader
